
- name: Instalamos paquetes de NFS
  dnf:
    name: "{{ nfs_packages }}"
    state: present
  become: yes

- name:  directorio NFS
  file:
    path: /srv/nfs
    state: directory
  become: yes

- name: Agregamos los masters al /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.master }}"
  become: yes
  
- name: Agregamos workers al /etc/exports
  lineinfile:
    dest: /etc/exports
    line: "/srv/nfs/ {{ hostvars[item].ansible_host }}(rw,sync)"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.workers }}"
  become: yes

- name: Habilitar NFS
  systemd:
    name: nfs-server
    state: started
    enabled: yes
    masked: no
  become: yes
  
- name: configuración del fichero /etc/exports
  shell: exportfs -r
  become: yes

- name: Habilitamos  nfs
  firewalld:
    service: nfs
    permanent: true
    state: enabled
  become: yes

- name: Habilitamos rpc-bind
  firewalld:
    service: rpc-bind
    permanent: true
    state: enabled
  become: yes

- name: Habilitamos servicios  mountd
  firewalld:
    service: mountd
    permanent: true
    state: enabled
  become: yes
  
- name: Reiniciando el servicio Firewalld 
  systemd:
    name: firewalld
    state: restarted
  become: yes
  
