---

- name: hostname
  hostname:
    name: "{{inventory_hostname}}.{{kubernets_domain}}"
    use: systemd
  when: inventory_hostname is regex("work*|master*|nfs*")
  become: yes

- name: DNS hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}} {{item}}.{{kubernets_domain}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
  become: yes

- name: Actualizando los paquetes del Sistema
  dnf:
    name: "*"
    state: latest
  become: yes
  
- name: Instalamos paquetes de Utilidades
  dnf:
    name: "{{ common_packages }}"
    state: present
  become: yes

- name: Deshabilitamos SELinux
  selinux:
    state: disabled
  become: yes

- name: Instalando Chrony
  dnf:
    name: chrony
    state: present
  become: yes


- name: timezone
  timezone:
    name: Europe/Madrid
  become: yes
  
- name: servicio Chronyd (Red Hat)
  systemd:
    name: chronyd
    state: started
    enabled: yes
    masked: no
  become: yes
