---

# Llamamos a todos los playbooks relacionados a la instalación de Kubernetes
  
# Ejecutamos las configuraciones comunes a todos los nodos
- import_playbook: comunes.yml
# Ejecutamos las configuraciones correspondientes a los nodos NFS
- import_playbook: nfs.yml
# Ejecutamos las configuraciones comunes a los masters y workers
- import_playbook: master-worker.yml
# Ejecutamos las configuraciones correspondientes a los nodos Master
- import_playbook: master.yml
# Ejecutamos las configuraciones correspondientes a los nodos Worker
- import_playbook: workers.yml
# Realizamos pruebas finales al cluster recién desplegado
- import_playbook: cluster.yml
