
- debug:
    msg: "El CERT Hash del master es: {{ cert_hash }}"
  when: cert_hash is defined

- debug:
    msg: "El Token Hash del master es: {{ token_hash }}"
  when: token_hash is defined
  
- debug:
    msg: "La IP del master es: {{ ip_master }}"
  when: ip_master is defined
  
- name: Habilitar puertos 10250
  firewalld:
    port: 10250/tcp
    permanent: true
    zone: public
    state: enabled
  become: yes
  
- name:  Habilitar puertos 30000 32767
  firewalld:
    port: 30000-32767/tcp
    permanent: true
    zone: public
    state: enabled
  become: yes
  
- name: Reinicio Firewalld 
  systemd:
    name: firewalld
    state: restarted
  become: yes
  
- name: Union Worker
  shell: "kubeadm join {{ ip_master }}:6443 --token {{ token_hash }} --discovery-token-ca-cert-hash sha256:{{ cert_hash }}"
  register: kubeadm_join
  become: yes
  
- name: Resultado
  debug:
    msg: "{{ kubeadm_join.stdout_lines }}"
  
